version: 2
jobs:
  test-python-2-7-14:
    docker:
      - image: circleci/python:2.7.14
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            source /home/circleci/repo/venv/bin/activate
            pip install -e .[test]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            pytest

  test-python-3-6:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            source /home/circleci/repo/venv/bin/activate
            pip install -e .[test]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            pytest
      - persist_to_workspace:
          root: .
          paths:
            - venv

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build and upload to geru-pypi
          command: |
            python setup.py sdist
            virtualenv venv
            ./venv/bin/pip install twine
            ./venv/bin/twine upload --repository-url https://geru-pypi.geru.com.br/ dist/*

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-python-2-7-14
      - test-python-3-6
      - deploy:
          requires:
            - test-python-2-7-14
            - test-python-3-6
          filters:
            branches:
              only:
                - master